services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=first_ms
    ports:
      - '54320:5432'
    volumes: 
      - ./.volumes/postgres:/var/lib/postgresql/data
    networks:
      - service1Network


networks:
  service1Network:
    driver: bridge

